version: '3'
services:
  lfsmaster:
    environment:
      - MASTER_HOST=192.168.10.10

  lfsmeta:
    environment:
      - MASTER_HOST=192.168.10.10

  lfscgi:
    environment:
      - MASTER_HOST=192.168.10.10

  lfschunk:
    environment:
      - MASTER_HOST=192.168.10.10
    volumes:
      # now we set the disk paths to use as chunkserver storage
      - ./mfs_chunkStorage1:/mnt/storage1
      - ./mfs_chunkStorage2:/mnt/storage2

